name: swift

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  # Build and test on multiple platforms
  build-and-test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["6.0.0"]
    steps:
    - uses: actions/checkout@v4
    
    # Fix GPG key issues before Swift setup (Ubuntu only)
    - name: Fix GPG keys (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        # Add the Swift key directly
        curl -fsSL https://swift.org/keys/all-keys.asc | sudo gpg --import --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/swift.gpg
        sudo chmod 644 /etc/apt/trusted.gpg.d/swift.gpg
        # Add the specific key that's causing issues
        curl -fsSL https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xEF80A866B47A981F | sudo gpg --import --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/custom.gpg
        sudo chmod 644 /etc/apt/trusted.gpg.d/custom.gpg
    
    - name: Setup Swift
      uses: SwiftyLab/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
        
    - name: Install D-Bus dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev dbus
        # Start D-Bus session for testing
        sudo dbus-launch --auto-syntax
        
    - name: Install D-Bus (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install dbus
        brew services start dbus
        
    - name: Build
      run: swift build -c release
      
    - name: Run tests with Swift Testing
      run: swift test