# Workflow name
name: swift

# Triggers for the workflow
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

# Jobs to run
jobs:
  build-and-test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest]
        # *** Use specific Swift 6.0.3 version ***
        swift: ["6.0.3"]

    steps:
    # 1. Check out repository code
    - name: Check out repository code
      uses: actions/checkout@v4

    # === Linux Setup (Ubuntu 22.04) ===
    # 2. (Linux Only) Ensure prerequisites are installed
    - name: Ensure Prerequisites (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update && sudo apt-get install -y \
          gpg dirmngr gzip curl wget \
          libatomic1 libncurses5
        mkdir -p ~/.gnupg
        chmod 700 ~/.gnupg
        echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf
        echo "Prerequisites installed, GPG configured."

    # 3. (Linux Only) Manually fetch, decompress, and import Swift keys
    - name: Manually Fetch and Import Swift Keys (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        echo "Manually downloading, decompressing, and importing Swift keys..."
        curl -fsSL https://swift.org/keys/all-keys.asc | gunzip | gpg --import -
        echo "Import process completed."
        # Assuming 6.x key still signs .3 release, otherwise adjust name if needed
        if gpg --list-keys 'Swift 6.x Release Signing Key'; then
          echo "Swift 6.x Release Signing key successfully imported/found."
        else
          echo "ERROR: Swift 6.x Release Signing Key not found after import attempt!" >&2
          exit 1
        fi

    # 4. (Linux Only) Manually Download, Verify, and Install Swift for Ubuntu 22.04
    - name: Manually Install Swift (Linux - Ubuntu 22.04)
      if: matrix.os == 'ubuntu-22.04'
      env:
        # matrix.swift will now be "6.0.3"
        SWIFT_VERSION: ${{ matrix.swift }}
      run: |
        UBUNTU_VERSION_NODOT="2204"
        SWIFT_PLATFORM="ubuntu${UBUNTU_VERSION_NODOT}"
        # These will now correctly use "6.0.3"
        SWIFT_BRANCH="swift-${SWIFT_VERSION}-release"
        SWIFT_VERSION_TAG="swift-${SWIFT_VERSION}-RELEASE"
        SWIFT_TARBALL_NAME="${SWIFT_VERSION_TAG}-${SWIFT_PLATFORM}.tar.gz"
        SWIFT_DOWNLOAD_URL="https://download.swift.org/${SWIFT_BRANCH}/${SWIFT_PLATFORM}/${SWIFT_VERSION_TAG}/${SWIFT_TARBALL_NAME}"

        echo "Downloading Swift from: ${SWIFT_DOWNLOAD_URL}"
        # Use curl for download
        if curl -fsSL "${SWIFT_DOWNLOAD_URL}" -o "${SWIFT_TARBALL_NAME}"; then
          echo "curl download succeeded."
        else
          echo "curl download FAILED! Exit code: $?" >&2
          exit 1
        fi

        echo "Downloading signature..."
        curl -fsSL "${SWIFT_DOWNLOAD_URL}.sig" -o "${SWIFT_TARBALL_NAME}.sig"

        echo "Verifying Swift download using GPG..."
        if gpg --verify "${SWIFT_TARBALL_NAME}.sig" "${SWIFT_TARBALL_NAME}"; then
           echo "GPG verification successful."
        else
           echo "GPG verification FAILED!" >&2
           exit 1
        fi

        echo "Extracting Swift toolchain..."
        mkdir swift_toolchain
        tar xzf "${SWIFT_TARBALL_NAME}" -C swift_toolchain --strip-components=1

        echo "Adding Swift to PATH..."
        SWIFT_PATH="$(pwd)/swift_toolchain/usr/bin"
        echo "SWIFT_PATH=${SWIFT_PATH}" >> $GITHUB_ENV
        echo "${SWIFT_PATH}" >> $GITHUB_PATH
        echo "Swift installed manually to ${SWIFT_PATH}"

    # === macOS Setup ===
    - name: Setup Swift (macOS)
      if: matrix.os == 'macos-latest'
      uses: swift-actions/setup-swift@v2
      with:
        # This should correctly fetch 6.0.3 on macOS too
        swift-version: ${{ matrix.swift }}

    # === Common Steps ===
    # 5. Verify Swift installation
    - name: Verify Swift installation
      run: swift --version

    # 6. Install D-Bus dependencies
    - name: Install D-Bus dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev dbus
        eval $(dbus-launch --auto-syntax)
        echo "D-Bus dependencies installed and session launched."
    - name: Install D-Bus (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install dbus
        echo "D-Bus installed via Homebrew (service not started)."

    # 7. Build the Swift package
    - name: Build Package
      run: swift build -c release -v

    # 8. Run tests
    - name: Run Tests (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: swift test -v
    - name: Explain Skipped Tests (macOS)
      if: matrix.os == 'macos-latest'
      run: echo "Skipping tests on macOS as they may depend on a D-Bus session environment."